import { CardDefinition } from '../types/cards';

export const CARD_REGISTRY: CardDefinition[] = [
  {
    id: 'header',
    title: 'Character Banner & Identity',
    shortTitle: 'Identity',
    category: 'overview',
    description: 'Character name, title, level, class, race, guild, and active career dates.',
    icon: '👑',
    defaultSelected: true,
  },
  {
    id: 'top_stats',
    title: 'Hero Metrics Bar',
    shortTitle: 'Hero Stats',
    category: 'overview',
    description: 'Top high-level stats: primary class action, AA count, pinnacles conquered, and mortality rate.',
    icon: '⚡',
    defaultSelected: true,
  },
  {
    id: 'pinnacle_bosses',
    title: '👑 Pinnacle Raid Bosses (First Kills)',
    shortTitle: 'Pinnacles',
    category: 'combat',
    description: 'First kills of dragons, gods, and era culminations with pqdi.cc links.',
    icon: '🐉',
    defaultSelected: true,
  },
  {
    id: 'top_raid_kills',
    title: '⚔️ Top Raid Boss Total Kills',
    shortTitle: 'Top Bosses',
    category: 'combat',
    description: 'The 6 to 10 most frequently defeated raid and event bosses.',
    icon: '⚔️',
    defaultSelected: true,
  },
  {
    id: 'class_mastery',
    title: '🕊️ Class Mastery & Primary Signature Spells',
    shortTitle: 'Class Mastery',
    category: 'combat',
    description: 'Signature class skills: Complete Healing, Bard songs, Enchanter CC, or Necromancer DoTs.',
    icon: '✨',
    defaultSelected: true,
  },
  {
    id: 'aa_points',
    title: '🌟 AA Points by Zone',
    shortTitle: 'AA Zones',
    category: 'progression',
    description: 'Breakdown of alternate advancement experience earned across Norrath and Luclin.',
    icon: '⭐',
    defaultSelected: true,
  },
  {
    id: 'mortality_nemesis',
    title: '☠️ Mortality & Nemesis',
    shortTitle: 'Nemesis',
    category: 'combat',
    description: 'Total deaths, top mob killers (Nemesis), environmental deaths, and rez recovery percentage.',
    icon: '☠️',
    defaultSelected: true,
  },
  {
    id: 'secondary_class',
    title: '🗡️ Secondary Class Utility & Combat',
    shortTitle: 'Secondary Utility',
    category: 'combat',
    description: 'Utility spells: Roots, Pacify, Yaulp, Bellows, Tashani, or secondary combat abilities.',
    icon: '🛡️',
    defaultSelected: true,
  },
  {
    id: 'social_circle',
    title: '💬 Companions in Arms & Social Circle',
    shortTitle: 'Social Circle',
    category: 'social',
    description: 'Top direct tell partners, group chat companions, and raid chat comrades.',
    icon: '💬',
    defaultSelected: true,
  },
  {
    id: 'milestones',
    title: '🏆 Milestones & Expansion Firsts',
    shortTitle: 'Milestones',
    category: 'progression',
    description: 'Dates of first footsteps into Kunark, Velious, Luclin, Ding 60, and Epic 1.0 acquisition.',
    icon: '🏆',
    defaultSelected: true,
  },
  {
    id: 'interactive_timeline',
    title: '📈 Interactive Career Timeline',
    shortTitle: 'Timeline Tool',
    category: 'interactive',
    description: 'Full 3-tier interactive timeline with draggable mini-map scrubber, date ticks, and monthly raid summaries.',
    icon: '📊',
    defaultSelected: true,
  },
];

export function getCardDefinition(id: string): CardDefinition | undefined {
  return CARD_REGISTRY.find((c) => c.id === id);
}
